// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-apps.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var APPS = [
  { id: "fileExplorer", title: "File Explorer", description: "Browse the virtual Ref OS file system." },
  { id: "notepad", title: "Notepad", description: "Write and save plain text notes." },
  { id: "calculator", title: "Calculator", description: "Basic arithmetic calculator." },
  { id: "settings", title: "Settings", description: "Personalization, account, alerts, privacy, system and about panels." },
  { id: "weather", title: "Weather", description: "Simulated weather forecast app." },
  { id: "calendar", title: "Calendar", description: "Month view calendar with events." },
  { id: "browser", title: "Web Browser", description: "Embedded browser that loads real websites in an iframe." },
  { id: "terminal", title: "Terminal", description: "Command line with easter eggs like hack and matrix." },
  { id: "refy", title: "Refy Assistant", description: "In-OS AI chat assistant." },
  { id: "movie", title: "RefMovies", description: "Video streaming app." },
  { id: "game", title: "RefGames", description: "Game center with arcade and touch friendly games." },
  { id: "email", title: "RefMail", description: "Mail client." },
  { id: "store", title: "Ref Store", description: "App store for Ref OS." },
  { id: "taskmanager", title: "Task Manager", description: "Monitor running apps and simulated resources." },
  { id: "updatecenter", title: "Update Center", description: "System update simulation." },
  { id: "music", title: "RefMusic", description: "Music player." },
  { id: "photos", title: "Photos", description: "Photo gallery." },
  { id: "paint", title: "Paint", description: "Simple drawing canvas." }
];
var list_apps_default = defineTool({
  name: "list_apps",
  title: "List Ref OS apps",
  description: "List the built-in applications available in the Ref OS desktop environment.",
  inputSchema: {
    search: z.string().describe("Optional case-insensitive filter matched against app title or description.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search }) => {
    const q = search?.trim().toLowerCase();
    const apps = q ? APPS.filter((a) => `${a.title} ${a.description}`.toLowerCase().includes(q)) : APPS;
    return {
      content: [{ type: "text", text: apps.map((a) => `${a.title} (${a.id}) \u2014 ${a.description}`).join("\n") || "No matching apps." }],
      structuredContent: { apps }
    };
  }
});

// src/lib/mcp/tools/list-games.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var GAMES = [
  { id: "snake", title: "Snake", input: "keyboard", category: "arcade" },
  { id: "pong", title: "Pong", input: "keyboard", category: "arcade" },
  { id: "tetris", title: "Tetris", input: "keyboard", category: "arcade" },
  { id: "breakout", title: "Breakout", input: "keyboard", category: "arcade" },
  { id: "2048", title: "2048", input: "touch", category: "puzzle" },
  { id: "flappy", title: "Flappy Bird", input: "touch", category: "arcade" },
  { id: "memory", title: "Memory Match", input: "touch", category: "puzzle" },
  { id: "colortap", title: "Simon Says", input: "touch", category: "memory" },
  { id: "builder", title: "Game Builder", input: "touch", category: "creative" }
];
var list_games_default = defineTool2({
  name: "list_games",
  title: "List RefGames titles",
  description: "List the games bundled in the RefGames game center, optionally filtered by input type.",
  inputSchema: {
    input: z2.enum(["keyboard", "touch"]).describe("Filter by primary input type.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ input }) => {
    const games = input ? GAMES.filter((g) => g.input === input) : GAMES;
    return {
      content: [{ type: "text", text: games.map((g) => `${g.title} \u2014 ${g.category}, ${g.input}`).join("\n") }],
      structuredContent: { games }
    };
  }
});

// src/lib/mcp/tools/list-terminal-commands.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var COMMANDS = [
  { command: "help", description: "Show the list of available commands." },
  { command: "echo <text>", description: "Print the given text back." },
  { command: "date", description: "Print the current date and time." },
  { command: "ls", description: "List files in the current virtual directory." },
  { command: "clear", description: "Clear the terminal output." },
  { command: "whoami", description: "Print the current Ref OS user." },
  { command: "version", description: "Print the Ref OS version." },
  { command: "hack", description: "Easter egg: cinematic multi-phase fake penetration test." },
  { command: "matrix", description: "Easter egg: Matrix rain animation overlay." }
];
var list_terminal_commands_default = defineTool3({
  name: "list_terminal_commands",
  title: "List terminal commands",
  description: "List the commands supported by the Ref OS Terminal app, including easter eggs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: COMMANDS.map((c) => `${c.command} \u2014 ${c.description}`).join("\n") }],
    structuredContent: { commands: COMMANDS }
  })
});

// src/lib/mcp/tools/get-system-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_system_info_default = defineTool4({
  name: "get_system_info",
  title: "Get Ref OS system info",
  description: "Return public information about Ref OS: version, vendor, boot flow, and supported input methods.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Ref OS",
      version: "2.0",
      vendor: "Brin Corporation",
      description: "A web-based desktop operating system simulation with a glass UI, windowing, and bundled apps.",
      bootFlow: ["BIOS/UEFI screen", "Boot screen with live boot.log", "Installer", "Out-of-box experience (OOBE)", "Desktop"],
      inputMethods: ["mouse", "keyboard", "touch (drag, resize, tap, edge swipe gestures)"],
      shell: ["Desktop icon grid", "Dock/taskbar", "Launchpad-style Start Menu", "Notification Center", "Draggable resizable windows"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "refosofficial",
  title: "refosofficial",
  version: "0.1.0",
  instructions: "Read-only tools describing Ref OS, a web-based desktop OS simulation. Use `get_system_info` for version and platform details, `list_apps` for bundled applications, `list_games` for the RefGames catalog, and `list_terminal_commands` for supported terminal commands.",
  tools: [list_apps_default, list_games_default, list_terminal_commands_default, get_system_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
