// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksinekpenvtfjqdgkyrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzaW5la3BlbnZ0ZmpxZGdreXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzAyOTAsImV4cCI6MjA2NTUwNjI5MH0.NqPv8swOMHxlEJJ8dbW3mDcwuSmmQj7kjc7V6GSIYaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);